- id: '1615523687503'
  alias: "\U0001F39BPool Set Temp - Current"
  description: Keep input_number in sync with pool controller's set temp
  trigger:
    - platform: time_pattern
      hours: '*'
      minutes: /30
      seconds: '0'
    - platform: state
      entity_id: sensor.pool
      attribute: SetTemp
  condition:
    - condition: template
      value_template: >-
        {{ state_attr('sensor.pool', 'SetTemp') !=
        states('input_number.pool_settemp') }}
  action:
    - service: input_number.set_value
      target:
        entity_id: input_number.pool_settemp
      data:
        value: '{{ state_attr(''sensor.pool'', ''SetTemp'') }}'
  mode: single
- id: '1615526380766'
  alias: "\U0001F39BPool Set Temp - Change"
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.pool_settemp
  condition: []
  action:
  - service: shell_command.set_pool_temp
  mode: single
