## Waterways Oasis

sensor:
  - platform: command_line
    name: pool
    json_attributes:
      - Mode
      - ModeNumber
      - PumpSpeed
      - PoolTemp
      - AirTemp
      - SolarTemp
      - SetTemp
      - Heat
      - aux1
      - aux2
      - aux3
      - aux4
      - aux5
      - aux6
      - aux7
      - aux8
      - aux9
      - j1
      - j2
      - j3
      - j4
    command: "/config/waterway/json.sh"
    value_template: "{{ value_json.Status }}"
    scan_interval: "6"
  - platform: template
    sensors:
      pool_mode:
        value_template: "{{ state_attr('sensor.pool', 'Mode') }}"
        friendly_name: "Pool Mode"
        icon_template: "mdi:air-filter"
      pool_temp:
        value_template: "{{ state_attr('sensor.pool', 'PoolTemp')|int }}"
        friendly_name: "Pool Temp"
        device_class: "temperature"
        unit_of_measurement: "째F"
      air_temp:
        value_template: "{{ state_attr('sensor.pool', 'AirTemp')|int }}"
        friendly_name: "Air Temp"
        device_class: "temperature"
        unit_of_measurement: "째F"
      solar_temp:
        value_template: "{{ state_attr('sensor.pool', 'SolarTemp')|int }}"
        friendly_name: "Solar Temp"
        device_class: "temperature"
        unit_of_measurement: "째F"
      pump_speed:
        value_template: "{{ state_attr('sensor.pool', 'PumpSpeed')|int  }}"
        friendly_name: "Pump Speed"
        unit_of_measurement: "%"
        icon_template: "mdi:pump"

# Comment out this section for lone pool system.
binary_sensor:
  - platform: template
    sensors:
      pool_intake_valve:
        friendly_name: "Intake Valve"
        value_template: "{{ is_state_attr('sensor.pool', 'j1', '1') }}"
        icon_template: mdi:relation-many-to-zero-or-one
      pool_return_valve:
        friendly_name: "Return Valve"
        value_template: "{{ is_state_attr('sensor.pool', 'j2', '1') }}"
        icon_template: mdi:relation-one-to-zero-or-many

input_number:
  pool_settemp:
    name: Pool Set Temp
    min: 74
    max: 99
    step: 1
    unit_of_measurement: "째F"
    mode: slider
    icon: "mdi:thermometer"

shell_command:
  set_pool_temp: "/config/waterway/setpool.sh settemp {{ states('input_number.pool_settemp') }}"
# Uncomment for lone pool system (and the applicable switch below)
#  pool_toggle: "/config/waterway/setpool.sh poolmode 1"
# Comment out these four for lone pool system (and the applicable switches below)
  off_mode: "/config/waterway/setpool.sh poolmode {{ ((state_attr('sensor.pool','ModeNumber')|int*-1)+0)%4 }}"
  pool_mode: "/config/waterway/setpool.sh poolmode {{ ((state_attr('sensor.pool','ModeNumber')|int*-1)+1)%4 }}"
  spillover_mode: "/config/waterway/setpool.sh poolmode {{ ((state_attr('sensor.pool','ModeNumber')|int*-1)+2)%4 }}"
  spa_mode: "/config/waterway/setpool.sh poolmode {{ ((state_attr('sensor.pool','ModeNumber')|int*-1)+3)%4 }}"
  
rest_command:
  pool_heat:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C15%2C%21%2CAA%2C55"
  pool_aux1:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C02%2C%21%2CAA%2C55"
  pool_aux2:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C03%2C%21%2CAA%2C55"
  pool_aux3:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C04%2C%21%2CAA%2C55"
  pool_aux4:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C05%2C%21%2CAA%2C55"
  pool_aux5:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C06%2C%21%2CAA%2C55"
  pool_aux6:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C07%2C%21%2CAA%2C55"
  pool_aux7:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C08%2C%21%2CAA%2C55"
  pool_aux8:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C09%2C%21%2CAA%2C55"
  pool_aux9:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C0A%2C%21%2CAA%2C55"
  pool_j1:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C0B%2C%21%2CAA%2C55"
  pool_j2:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C0C%2C%21%2CAA%2C55"
  pool_j3:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C0D%2C%21%2CAA%2C55"
  pool_j4:
    url: "http://192.168.22.5/index.htm?txtValue=%24A0%2C6%2C0E%2C%21%2CAA%2C55"

switch:
  - platform: template
    switches:
## Uncomment for lone pool system
#      pool:
#        friendly_name: "Pool"
#        value_template: "{{ is_state('sensor.pool', 'on') }}"
#        turn_on:
#          - service: shell_command.pool_toggle
#        turn_off:
#          - service: shell_command.pool_toggle
#        icon_template: "mdi:waves"
## Comment out next three (pool_mode,spillover_mode,spa_mode) for lone pool system
      pool_mode:
        friendly_name: "Pool"
        value_template: "{{ is_state_attr('sensor.pool', 'Mode', 'Pool') }}"
        turn_on:
          - service: shell_command.pool_mode
        turn_off:
          - service: shell_command.off_mode
        icon_template: "mdi:waves"
      spillover_mode:
        friendly_name: "Spillover"
        value_template: "{{ is_state_attr('sensor.pool', 'Mode', 'Spillover') }}"
        turn_on:
          - service: shell_command.spillover_mode
        turn_off:
          - service: shell_command.off_mode
        icon_template: "mdi:archive-arrow-down-outline"
      spa_mode:
        friendly_name: "Spa"
        value_template: "{{ is_state_attr('sensor.pool', 'Mode', 'Spa') }}"
        turn_on:
          - service: shell_command.spa_mode
        turn_off:
          - service: shell_command.off_mode
        icon_template: "mdi:hot-tub"
      pool_heat:
        friendly_name: "Heat"
        value_template: "{{ is_state_attr('sensor.pool', 'Heat', '1') }}"
        turn_on:
          - service: rest_command.pool_heat
        turn_off:
          - service: rest_command.pool_heat
        icon_template: "mdi:hot-tub"
      spa_light:
        friendly_name: "Spa Light"
        value_template: "{{ is_state_attr('sensor.pool', 'aux1', '1') }}"
        turn_on:
          - service: rest_command.pool_aux1
        turn_off:
          - service: rest_command.pool_aux1
        icon_template: mdi:lightbulb
      pool_solar:
        friendly_name: "Pool Solar"
        value_template: "{{ is_state_attr('sensor.pool', 'j3', '1') }}"
        turn_on:
          - service: rest_command.pool_j3
        turn_off:
          - service: rest_command.pool_j3
        icon_template: "mdi:weather-sunny"


automation waterway:
  - alias: "\U0001F39BPool Set Temp - Current"
    description: Keep input_number in sync with pool controller's set temp
    trigger:
      - platform: time_pattern
        hours: '*'
        minutes: /30
        seconds: '0'
      - platform: state
        entity_id: sensor.pool
        attribute: SetTemp
    condition:
      - condition: template
        value_template: >-
          {{ state_attr('sensor.pool', 'SetTemp')|int !=
          states('input_number.pool_settemp')|int }}
      - condition: template
        value_template: '{{ state_attr(''sensor.pool'', ''SetTemp'')|int != 0 }}'
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.pool_settemp
        data:
          value: '{{ state_attr(''sensor.pool'', ''SetTemp'')|float }}'
    mode: single
  - alias: "\U0001F39BPool Set Temp - Change"
    description: ''
    trigger:
      - platform: state
        entity_id: input_number.pool_settemp
    condition: []
    action:
      - service: shell_command.set_pool_temp
    mode: single
